version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  web:
    image: odoo:15
    depends_on:
      - db
    environment:
      - HOST=db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "8069:8069"  # Keep this port for Odoo's longpolling mechanism
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  nginx:
    image: nginx:1.25
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - odoo-web-data:/var/lib/odoo  # For static files

volumes:
  odoo-db-data:
  odoo-web-data:

